export const TABS_INITIALIZE = 'TABS_INITIALIZE';
export const TAB_SWITCH = 'TAB_SWITCH';

export const TABS_RECEIVE = 'TABS_RECEIVE';
export const TAB_DELETE = 'TAB_DELETE';
export const ACTIVE_TAB_UPDATE = 'UPDATE_ACTIVE_TAB';

export const SETTING_UPDATE = 'SETTING_UPDATE';
