export const TABS_INITIALIZE = 'TABS_INITIALIZE';

export const TABS_RECEIVE = 'TABS_RECEIVE';
export const TAB_DELETE = 'TAB_DELETE';
export const ACTIVE_TAB_UPDATE = 'UPDATE_ACTIVE_TAB';

export const FUZZY = 'FUZZY/';
export const CHECKBOX_UPDATE = 'CHECKBOX_UPDATE';
export const RANGE_UPDATE = 'RANGE_UPDATE';
export const SEARCH_KEY_UPDATE = 'SEARCH_KEY_UPDATE';
