// Settings
export const FUZZY = 'FUZZY/';
export const CHECKBOX_UPDATE = 'CHECKBOX_UPDATE';
export const RANGE_UPDATE = 'RANGE_UPDATE';
export const SEARCH_KEY_UPDATE = 'SEARCH_KEY_UPDATE';
export const SETTINGS_RESET = 'SETTINGS_RESET';
export const NUMBER_UPDATE = 'NUMBER_UPDATE';
export const SETTING_RESET = 'SETTING_RESET';
export const COLOR_UPDATE = 'COLOR_UPDATE';

// State
export const LAST_QUERY_UPDATE = 'LAST_QUERY_UPDATE';

// Keyboard
export const KEYBINDING_UPDATE = 'KEYBINDING_UPDATE';
export const KEYBINDING_DEFAULT_RESET = 'KEYBINDING_DEFAULT_RESET';
